### ISSUE TITLE
siphon-fx.com down!

### ISSUE THREAD

**Issue by markwu** [ianhalpern/Siphon#1]
Hi Ian:

Sorry to report the issue here, the siphon-fx.com seems down for several days. Would you kindly fix it? 

Mark

**Comment by ianhalpern** [comment]
Fixed! Whoops, I've been so busy I had no idea the server was down. I'll 
put a monitor on that server so this doesn't happen again. I appreciate 
the heads up!

Best,
Ian

**Comment by markwu** [comment]
Great thanks!!!

**Comment by ilya-paskhover** [comment]
Seems like server is down again... :(

**Comment by ianhalpern** [comment]
Back up...again! sorry

**Comment by ghost** [comment]
It's currently not working.

**Comment by ianhalpern** [comment]
Sorry, should be back up.

**Comment by ghost** [comment]
Yes, it works now. Thank you very much!

**Comment by ghost** [comment]
Siphon is down again.

**Comment by ghost** [comment]
Not working.

**Comment by ghost** [comment]
It stopped again.

**Comment by ghost** [comment]
Thanks for fixing it.

**Comment by ghost** [comment]
Won't sync.

**Comment by djadk84** [comment]
Service is down again could you please fix?

**Comment by h4ckrn00b** [comment]
Service is down again could you please fix?

**Comment by h4ckrn00b** [comment]
Is this some sort of OCTOBER surprise thing  ;)
